apiVersion: sources.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: githubsourcesample
  namespace: default
spec:
  eventTypes:
    - check_suite
    - commit_comment
    - create
    - delete
    - deployment
    - deployment_status
    - fork
    - gollum
    - installation
    - integration_installation
    - issue_comment
    - issues
    - label
    - member
    - membership
    - milestone
    - organization
    - org_block
    - page_build
    - ping
    - project_card
    - project_column
    - project
    - public
    - pull_request
    - pull_request_review
    - pull_request_review_comment
    - push
    - release
    - repository
    - status
    - team
    - team_add
    - watch
  ownerAndRepository: dashaun/dev.dashaun.service.gateway
  accessToken:
    secretKeyRef:
      name: githubsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: githubsecret
      key: secretToken
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: github-message-dumper